# config.yaml

# Paramètres du modèle
model:
  onnx_model_path: "./models/Phi-3.5-mini-instruct-onnx"
  
# Paramètres de génération
generation:
  temperature: 0.1
  max_new_tokens: 1000
#  top_p: 0.95
#  top_k: 50

# Fichiers
paths:
  logs: "./logs"
  output: "./output"

# Paramètres du nettoyage du texte
cleaning:
  remove_newlines: true
  remove_spaces: true

# Paramètres de la classification des expériences professionnelles
classification:
  min_experience_months: 8
  exclude_types:
    - "Stage"
    - "Alternance"
    - "Freelance"
    - "Projet personnel"
